networks:
  slordefweb-dev:

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: slordef
      POSTGRES_PASSWORD: slordef
      POSTGRES_DB: slordef
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - slordefweb-dev

volumes:
  postgres_data:
